language: ruby
rvm:
  - 2.6.1
before_install:
  - gem update --system
  - gem install bundler
before_script:
  - bin/bundle rake db:create --all
  - bin/bundle rake db:migrate
script:
  - bin/rails test
services:
  - postgresql
notifications:
  email: false
